// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnhXJnjhpDh3bJXOxK4hb7CRcU1p2gHWc',
    appId: '1:712585116915:web:94a73527420152e74f8b86',
    messagingSenderId: '712585116915',
    projectId: 'libreria-zaitec',
    authDomain: 'libreria-zaitec.firebaseapp.com',
    storageBucket: 'libreria-zaitec.firebasestorage.app',
    measurementId: 'G-TZXFZYGSD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn5nqR_bNIa5P1PWm5swAXhHwqxH1gjww',
    appId: '1:712585116915:android:ac81711005467e064f8b86',
    messagingSenderId: '712585116915',
    projectId: 'libreria-zaitec',
    storageBucket: 'libreria-zaitec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgybIejUM5iZfPgsy3Qq1aQgl_4imzVs',
    appId: '1:712585116915:ios:65d42e2f6f1a12574f8b86',
    messagingSenderId: '712585116915',
    projectId: 'libreria-zaitec',
    storageBucket: 'libreria-zaitec.firebasestorage.app',
    iosBundleId: 'com.example.libreriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsgybIejUM5iZfPgsy3Qq1aQgl_4imzVs',
    appId: '1:712585116915:ios:65d42e2f6f1a12574f8b86',
    messagingSenderId: '712585116915',
    projectId: 'libreria-zaitec',
    storageBucket: 'libreria-zaitec.firebasestorage.app',
    iosBundleId: 'com.example.libreriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnhXJnjhpDh3bJXOxK4hb7CRcU1p2gHWc',
    appId: '1:712585116915:web:f11b7631f91f29f44f8b86',
    messagingSenderId: '712585116915',
    projectId: 'libreria-zaitec',
    authDomain: 'libreria-zaitec.firebaseapp.com',
    storageBucket: 'libreria-zaitec.firebasestorage.app',
    measurementId: 'G-22PMK0S656',
  );

}